### ISSUE TITLE
Benutzer: Profil, Einladen

### ISSUE THREAD

**Issue by robogito** [robogito/kubus#12]
- Pflichtfelder?

Profil
- Vorname und Nachname dürfen nicht optional sein

Einladen
- Absenden ohne Eingabe ist möglich, als Meldung wird nur "inviteUser.toast.invite.empty" angezeigt
- Email-Adressen werden nicht validiert, Eingabe von name@mail geht auch durch
- Andere Trennzeichen (z.B. Semikolon) werden akzeptiert, aber nicht verarbeitet

**Comment by luflow** [comment]
Vorname und Nachname dürfen nicht optional sein
- das ist leider nicht ganz so einfach, weil bspw. Einladungen immer ohne Vor/Nachname passieren, ergo anfangs Profile auch ohne Vor-und Nachname existieren.
- Im Checkout - also spätestens dann,wenn man etwas bucht, wird es aber zur Pflicht.

Einladen:
- nehme ich mit als Bugticket :)

**Comment by robogito** [comment]
Hier ist das Formular unter "Mein Profil" -> "Details" gemeint. In diesem Formular dürfen die Felder Vorname und Nachname nicht optional sein.
