### ISSUE TITLE
Kursangebote: Name soll eindeutig sein

### ISSUE THREAD

**Issue by robogito** [robogito/kubus#13]
Der Name des Kursangebots (Sportart) soll eindeutig sein. Das soll beim Erstellen und Bearbeiten (Duplizieren) berücksichtigt werden.

**Comment by ppreuss-ubo** [comment]
Aktuell nutzen wir eine Kursnummersystematik, die auch Grundlage für die Kostenstellen in Buchhaltung ist.
Eine solche Systematik ist nicht zwingend, erleichtert aber Strukturierung und Zuordnung.
In UniNow ist die offensichtlich die ID die Kursnummer.

Meine offenen Fragen:
ID als Pflichtfeld? Verhindert somit Duplikate.
Wird die ID irgendwo im System irgendwann automatisch vergeben, um eine eindeutige Zuordnung zu gewährleistenß

**Comment by robogito** [comment]
Eine ID kann dem Kurs vergeben werden, aber wir können ja nicht alle zwingen das zu tun, weil wir eine Systematik haben.
Kurse haben eine aut. ID (z.B. 14ea662d-a113-41df-9d51-5f85efa591b3). Falls wir sowas wie Kurs-Nr/Vertrags-Nr/Personal-Nr/Auftrags-Nr/Abo-Nr/Vermietungs-Nr in einer einfachen menschenlesbarer Form (z.B. 10001) benötigen, dann muss es als eine Anforderung für bestimmte System-Objekte deklariert werden.

**Comment by luflow** [comment]
Lasst uns das als Thema am Freitag mitnehmen!

**Comment by luflow** [comment]
Kursangebotsnamen können innerhalb einer Kursgruppe (z.B. Sportkurse) nicht mehr doppelt benutzt werden
