### ISSUE TITLE
Chatwoot fehlerhaft implementiert

### ISSUE THREAD

**Issue by robogito** [robogito/kubus#17]
Konsole: 404 (Not Found)

**Comment by luflow** [comment]
Steps to reproduce bitte.

**Comment by robogito** [comment]
Anmelden, DevTools öffnen, Konsole zeigt:

POST https://chatwoot.XXXXXXX.io/api/v1/widget/conversations/set_custom_attributes?website_token=8gYHg7TyHhgmuyqZgVoN9jdv&cw_conversation=eyJhbGciOiJIUzI1NiJ9.eyJzb3VyY2VfaWQiOiI2NTg2YmJmZS02MWU4LTQ2NzEtYTc4ZS00OWU5ZWRjODcyZjEiLCJpbmJveF9pZCI6Mn0.i3Po0bl66449wXqisBmEY4IfQhAPkqzp6RhHxISEukM
404 (Not Found)
