### ISSUE TITLE
Kurs Details: Termine werden nicht korrekt aktualisiert, wenn der Kurszeitraum (Wochentag) nachträglich geändert wird

### ISSUE THREAD

**Issue by robogito** [robogito/kubus#18]
Die Tabelle der Termine soll entsprechend den Einstellungen (Wochentag) aktualisiert werden.

**Comment by luflow** [comment]
Kannst du mir Steps2Reproduce schicken? Es gibt edge cases wo keine Termine mehr geändert werden - bspw. wenn der Termin in der Vergangenheit liegt, wird er nicht mehr angefasst. (ist ja vorbei)

**Comment by robogito** [comment]
- Einen neuen Kurs eintragen
- Termine und Kursdetails (Zeit & Ort) anschauen
- Den Tag ändern
- Termine und Kursdetails (Zeit & Ort) anschauen
- Einen zweiten Tag hinzufügen
- Termine und Kursdetails (Zeit & Ort) anschauen
- Den zweiten Tag ändern
- Termine und Kursdetails (Zeit & Ort) anschauen
