### ISSUE TITLE
Kurs Details: Teilnehmende hinzufügen - ausgewählten Eintrag anzeigen

### ISSUE THREAD

**Issue by robogito** [robogito/kubus#19]
Nach der Auswahl soll der Eintrag im Suchfeld angezeigt werden.

**Comment by luflow** [comment]
Hab ich nicht verstanden - hast du einen Screenshot und/oder steps to reproduce?

**Comment by robogito** [comment]
- "Kurs Details" eines beibiegen Kurses anzeigen
- Auf "Teilnehmende" klicken
- Auf den Button "Hinzufügen" klicken
- Im Modal-Fenster "Teilnehmer hinzufügen" nach E-Mail/Name suchen, auswählen
- Der gewählte Eintrag wird im Suchfeld nicht angezeigt
